[package]
name = "vaero-core"
description = "Policy and orchestration primitives for Vaero"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
getrandom.workspace = true
vaero-crypto = { version = "0.0.1", path = "../vaero-crypto" }

[lints]
workspace = true
